name: JabberPoint DTAP Pipeline

on:
  push:
    branches: [main, development, test, acceptance]
  pull_request:
    branches: [main, development, test, acceptance]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
      - name: Run tests with JaCoCo
        run: mvn test jacoco:report
      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/

  code-quality:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
      - name: Check code coverage
        run: mvn verify

  deploy-to-test:
    if: github.ref == 'refs/heads/test' || (github.event_name == 'pull_request' && github.base_ref == 'test')
    needs: code-quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
      - name: Package application
        run: mvn package -DskipTests
      - name: Deploy to Test Environment
        run: echo "Deploying to Test environment"

  deploy-to-acceptance:
    if: github.ref == 'refs/heads/acceptance' || (github.event_name == 'pull_request' && github.base_ref == 'acceptance')
    needs: code-quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
      - name: Package application
        run: mvn package -DskipTests
      - name: Deploy to Acceptance Environment
        run: echo "Deploying to Acceptance environment"

  deploy-to-production:
    if: github.ref == 'refs/heads/main' || (github.event_name == 'pull_request' && github.base_ref == 'main')
    needs: code-quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
      - name: Package application
        run: mvn package -DskipTests
      - name: Deploy to Production Environment
        run: echo "Deploying to Production environment"
